name: Build & Publish Installers


permissions:
  contents: write
  actions: write
  
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ['3.12']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --clean --noconfirm NexumAI.spec
        # Output is in dist/NexumAI[.exe|.app|]

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: NexumAI-${{ matrix.os }}
          path: |
            dist/**
            !dist/**/*.log

  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: installers

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload installers to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            installers/NexumAI-macos-latest
            installers/NexumAI-ubuntu-latest
            installers/NexumAI-windows-latest
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          
